# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/daetoya/files/chat_dialog_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class CreatingChatDialogDefault(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(757, 604)
        self.members_line = QtWidgets.QLineEdit(Dialog)
        self.members_line.setGeometry(QtCore.QRect(40, 100, 561, 41))
        self.members_line.setObjectName("members_line")

        self.add_members_button = QtWidgets.QPushButton(Dialog)
        self.add_members_button.setGeometry(QtCore.QRect(610, 100, 101, 41))
        self.add_members_button.setObjectName("add_members_button")

        self.confirm_button = QtWidgets.QPushButton(Dialog)
        self.confirm_button.setGeometry(QtCore.QRect(580, 540, 151, 41))
        self.confirm_button.setObjectName("confirm_button")

        self.cancel_button = QtWidgets.QPushButton(Dialog)
        self.cancel_button.setGeometry(QtCore.QRect(400, 540, 151, 41))
        self.cancel_button.setObjectName("cancel_button")

        self.chat_name_line = QtWidgets.QLineEdit(Dialog)
        self.chat_name_line.setGeometry(QtCore.QRect(90, 30, 561, 41))
        self.chat_name_line.setText("")
        self.chat_name_line.setObjectName("chat_name_line")

        self.added_member_scroll_area = QtWidgets.QScrollArea(Dialog)
        self.added_member_scroll_area.setGeometry(QtCore.QRect(40, 170, 671, 61))
        self.added_member_scroll_area.setWidgetResizable(True)
        self.added_member_scroll_area.setObjectName("added_member_scroll_area")

        self.added_members_widget = QtWidgets.QWidget()
        self.added_members_widget.setGeometry(QtCore.QRect(0, 0, 669, 59))
        self.added_members_widget.setObjectName("added_members_widget")
        self.added_members_widget.setSizePolicy(
            QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        )

        self.added_members_horizontal_layout = QtWidgets.QHBoxLayout(self.added_members_widget)
        self.added_members_horizontal_layout.setContentsMargins(0, 0, 0, 0)
        self.added_members_horizontal_layout.setSpacing(10)

        self.added_member_scroll_area.setWidget(self.added_members_widget)

        self.select_members_scroll_area = QtWidgets.QScrollArea(Dialog)
        self.select_members_scroll_area.setGeometry(QtCore.QRect(160, 270, 441, 231))
        self.select_members_scroll_area.setWidgetResizable(True)
        self.select_members_scroll_area.setObjectName("select_members_scroll_area")

        self.select_members_widget = QtWidgets.QWidget()
        self.select_members_widget.setGeometry(QtCore.QRect(0, 0, 439, 229))
        self.select_members_widget.setObjectName("select_members_widget")
        self.select_members_widget.setSizePolicy(
            QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        )

        self.select_members_vertical_layout = QtWidgets.QVBoxLayout(self.select_members_widget)
        self.select_members_vertical_layout.setContentsMargins(0, 0, 0, 0)
        self.select_members_vertical_layout.setSpacing(10)

        self.select_members_scroll_area.setWidget(self.select_members_widget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.add_members_button.setText(_translate("Dialog", "Add"))
        self.confirm_button.setText(_translate("Dialog", "Confirm"))
        self.cancel_button.setText(_translate("Dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = CreatingChatDialogDefault()
    ui.setupUi(Dialog)

    Dialog.show()


    sys.exit(app.exec_())
