CREATE TABLE "User" (
    id SERIAL PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    nickname TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Chat (
    id SERIAL PRIMARY KEY,
    chat_name TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Connect (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES "User"(id) ON DELETE CASCADE,
    chat_id INTEGER NOT NULL REFERENCES Chat(id) ON DELETE CASCADE
);

CREATE TABLE Message (
    id SERIAL PRIMARY KEY,
    chat_id INTEGER NOT NULL REFERENCES Chat(id) ON DELETE CASCADE,
    sender_id INTEGER NOT NULL REFERENCES "User"(id) ON DELETE CASCADE,
    content_text TEXT NOT NULL,
    sent_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE MessageVersion (
    id SERIAL PRIMARY KEY,
    message_id INTEGER NOT NULL REFERENCES Message(id) ON DELETE CASCADE,
    content_text TEXT NOT NULL,
    valid_from TIMESTAMP NOT NULL,
    valid_to TIMESTAMP NULL
);

CREATE TABLE Channel (
    id SERIAL PRIMARY KEY,
    channel_name TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    owner_id INTEGER NOT NULL REFERENCES "User"(id) ON DELETE CASCADE
);

CREATE TABLE Post (
    id SERIAL PRIMARY KEY,
    channel_id INTEGER NOT NULL REFERENCES Channel(id) ON DELETE CASCADE,
    author_id INTEGER NOT NULL REFERENCES "User"(id) ON DELETE CASCADE,
    content_text TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Subscription (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES "User"(id) ON DELETE CASCADE,
    channel_id INTEGER NOT NULL REFERENCES Channel(id) ON DELETE CASCADE,
    subscribed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
