# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/daetoya/files/chat_main_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ChatInterface(object):
    def setupUi(self, ChatInterface):
        ChatInterface.setObjectName("ChatInterface")
        ChatInterface.resize(1400, 1000)
        self.chats_scroll_area = QtWidgets.QScrollArea(ChatInterface)
        self.chats_scroll_area.setGeometry(QtCore.QRect(20, 110, 321, 791))
        self.chats_scroll_area.setWidgetResizable(True)
        self.chats_scroll_area.setObjectName("chats_scroll_area")

        self.chats_widget = QtWidgets.QWidget()
        self.chats_widget.setGeometry(QtCore.QRect(0, 0, 319, 789))
        self.chats_widget.setObjectName("chats_widget")
        self.chats_widget.setSizePolicy(
            QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        )

        self.chats_vertical_layout = QtWidgets.QVBoxLayout(self.chats_widget)
        self.chats_vertical_layout.setContentsMargins(0, 0, 0, 0)
        self.chats_vertical_layout.setSpacing(10)
        self.chats_vertical_layout.setAlignment(QtCore.Qt.AlignTop)

        self.chats_scroll_area.setWidget(self.chats_widget)

        self.chat_display_text_edit = QtWidgets.QTextEdit(ChatInterface)
        self.chat_display_text_edit.setGeometry(QtCore.QRect(360, 40, 1021, 831))
        self.chat_display_text_edit.setObjectName("chat_display_text_edit")
        self.send_button = QtWidgets.QPushButton(ChatInterface)
        self.send_button.setGeometry(QtCore.QRect(1310, 900, 71, 71))
        self.send_button.setObjectName("send_button")
        self.search_line = QtWidgets.QLineEdit(ChatInterface)
        self.search_line.setGeometry(QtCore.QRect(20, 40, 321, 41))
        self.search_line.setText("")
        self.search_line.setObjectName("search_line")
        self.new_chat_button = QtWidgets.QPushButton(ChatInterface)
        self.new_chat_button.setGeometry(QtCore.QRect(20, 930, 321, 41))
        self.new_chat_button.setObjectName("new_chat_button")
        self.message_plain_text = QtWidgets.QPlainTextEdit(ChatInterface)
        self.message_plain_text.setGeometry(QtCore.QRect(363, 900, 931, 71))
        self.message_plain_text.setObjectName("message_plain_text")

        self.retranslateUi(ChatInterface)
        QtCore.QMetaObject.connectSlotsByName(ChatInterface)

    def retranslateUi(self, ChatInterface):
        _translate = QtCore.QCoreApplication.translate
        ChatInterface.setWindowTitle(_translate("ChatInterface", "Form"))
        self.send_button.setText(_translate("ChatInterface", "Send"))
        self.new_chat_button.setText(_translate("ChatInterface", "Новый чат"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QWidget()
    ui = ChatInterface()
    ui.setupUi(Dialog)

    Dialog.show()


    sys.exit(app.exec_())
