# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/daetoya/files/chat_registration_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class RegistrationInterface(object):
    def setupUi(self, RegistrationInterface):
        RegistrationInterface.setObjectName("RegistrationInterface")
        RegistrationInterface.resize(1400, 1000)
        self.email_line = QtWidgets.QLineEdit(RegistrationInterface)
        self.email_line.setGeometry(QtCore.QRect(510, 340, 511, 41))
        self.email_line.setObjectName("email_line")
        self.username_line = QtWidgets.QLineEdit(RegistrationInterface)
        self.username_line.setGeometry(QtCore.QRect(510, 410, 511, 41))
        self.username_line.setObjectName("username_line")
        self.password_line = QtWidgets.QLineEdit(RegistrationInterface)
        self.password_line.setGeometry(QtCore.QRect(510, 480, 511, 41))
        self.password_line.setObjectName("password_line")
        self.nickname_line = QtWidgets.QLineEdit(RegistrationInterface)
        self.nickname_line.setGeometry(QtCore.QRect(510, 550, 511, 41))
        self.nickname_line.setObjectName("nickname_line")
        self.registration_label = QtWidgets.QLabel(RegistrationInterface)
        self.registration_label.setGeometry(QtCore.QRect(560, 180, 321, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.registration_label.setFont(font)
        self.registration_label.setObjectName("registration_label")
        self.email_label = QtWidgets.QLabel(RegistrationInterface)
        self.email_label.setGeometry(QtCore.QRect(400, 340, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.email_label.setFont(font)
        self.email_label.setObjectName("email_label")
        self.username_label = QtWidgets.QLabel(RegistrationInterface)
        self.username_label.setGeometry(QtCore.QRect(330, 410, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.username_label.setFont(font)
        self.username_label.setObjectName("username_label")
        self.password_label = QtWidgets.QLabel(RegistrationInterface)
        self.password_label.setGeometry(QtCore.QRect(340, 480, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.password_label.setFont(font)
        self.password_label.setObjectName("password_label")
        self.nickname_label = QtWidgets.QLabel(RegistrationInterface)
        self.nickname_label.setGeometry(QtCore.QRect(340, 550, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.nickname_label.setFont(font)
        self.nickname_label.setObjectName("nickname_label")
        self.next_button = QtWidgets.QPushButton(RegistrationInterface)
        self.next_button.setGeometry(QtCore.QRect(1100, 870, 211, 61))
        self.next_button.setObjectName("next_button")
        self.exit_button = QtWidgets.QPushButton(RegistrationInterface)
        self.exit_button.setGeometry(QtCore.QRect(850, 870, 211, 61))
        self.exit_button.setObjectName("exit_button")
        self.authorization_button = QtWidgets.QPushButton(RegistrationInterface)
        self.authorization_button.setGeometry(QtCore.QRect(10, 20, 191, 41))
        self.authorization_button.setObjectName("authorization_button")

        self.retranslateUi(RegistrationInterface)
        QtCore.QMetaObject.connectSlotsByName(RegistrationInterface)

    def retranslateUi(self, RegistrationInterface):
        _translate = QtCore.QCoreApplication.translate
        RegistrationInterface.setWindowTitle(_translate("RegistrationInterface", "Form"))
        self.registration_label.setText(_translate("RegistrationInterface", "Регистрация"))
        self.email_label.setText(_translate("RegistrationInterface", "email:"))
        self.username_label.setText(_translate("RegistrationInterface", "username:"))
        self.password_label.setText(_translate("RegistrationInterface", "password:"))
        self.nickname_label.setText(_translate("RegistrationInterface", "nickname:"))
        self.next_button.setText(_translate("RegistrationInterface", "Далее"))
        self.exit_button.setText(_translate("RegistrationInterface", "Выйти"))
        self.authorization_button.setText(_translate("RegistrationInterface", "Авторизация"))
